language: go

go:
- 1.14

before_install:
- chmod 777 go.test.sh

script:
- ./go.test.sh

after_success:
- bash <(curl -s https://codecov.io/bash) CODECOV_TOKEN="cd0c63ed-921b-4d67-a438-8cd3239c0c2f"
